#!/bin/tcsh -xef

echo "auto-generated by afni_proc.py, Fri Feb  2 14:28:45 2018"
echo "(version 6.02, December 12, 2017)"
echo "execution started: `date`"

# execute via : 
#   tcsh -xef proc.s6006 |& tee output.proc.s6006

# =========================== auto block: setup ============================
# script setup

# take note of the AFNI version
afni -ver

# check that the current AFNI version is recent enough
afni_history -check_date 23 Sep 2016
if ( $status ) then
    echo "** this script requires newer AFNI binaries (than 23 Sep 2016)"
    echo "   (consider: @update.afni.binaries -defaults)"
    exit
endif

#rm X* fitts* errts* stats*

# the user may specify a single subject to run with
if ( $#argv > 0 ) then
    set subj = $argv[1]
else
    set subj = s6006
endif

# ------------------------------
# run the regression analysis
3dDeconvolve -input pb04.$subj.r*.scale+tlrc.HEAD                        \
    -censor motion_${subj}_censor.1D                                     \
    -polort 2                                                            \
    -num_stimts 7                                                        \
    -stim_times_AM2 1 stimuli/${subj}allfMRI_demeaned.1D 'dmBLOCK'               \
    -stim_label 1 ${subj}allfMRI_demeaned.1D                                     \
    -stim_file 2 motion_demean.1D'[0]' -stim_base 2 -stim_label 2 roll   \
    -stim_file 3 motion_demean.1D'[1]' -stim_base 3 -stim_label 3 pitch  \
    -stim_file 4 motion_demean.1D'[2]' -stim_base 4 -stim_label 4 yaw    \
    -stim_file 5 motion_demean.1D'[3]' -stim_base 5 -stim_label 5 dS     \
    -stim_file 6 motion_demean.1D'[4]' -stim_base 6 -stim_label 6 dL     \
    -stim_file 7 motion_demean.1D'[5]' -stim_base 7 -stim_label 7 dP     \
    -jobs 8                                                              \
    -fout -tout -x1D X.xmat_cfg_demeaned.1D -xjpeg X_cfg_demeaned.jpg                              \
    -x1D_uncensored X.nocensor.xmat_cfg_demeaned.1D                                   \
    -fitts fitts_cfg_demeaned.$subj                                                   \
    -errts errts_cfg_demeaned.${subj}                                                 \
    -bucket stats_cfg_demeaned.$subj


# if 3dDeconvolve fails, terminate the script
if ( $status != 0 ) then
    echo '---------------------------------------'
    echo '** 3dDeconvolve error, failing...'
    echo '   (consider the file 3dDeconvolve.err)'
    exit
endif
